### ISSUE TITLE
annotateCircs() returns a variety of gene_id values for circs with both flanks intergenic

### ISSUE THREAD

**Issue by retaj** [BIMSBbioinfo/ciRcus#16]
o_O
```
> table(circs.diff.dt[feature=="intergenic:intergenic"]$gene_id)

                 0 ENSMUSG00000062352         intergenic     no_single_host 
                28                  1                303               1851 
```

**Comment by mschilli87** [comment]
Is that a new 'feature' or was it always like that and we just missed it in previous versions?
Did try to install from `master` or even older (poor man's `git bisect`)?

**Comment by retaj** [comment]
It is also broken in master. Not sure if it ever worked properly, but given that we have ~0 users, I will not waste time investigating :)

**Comment by retaj** [comment]
There are still situations where an intergenic circRNA gets a gene ID, but these are either caused by external annotation (see Ensembl 75 for chr12:109447067-109451813) or legit (two non-overlapping transcirpts of the same gene). These could be handled differently but are very rare + current solution is not wrong so I'll close this...
