### ISSUE TITLE
make loadAnnotation() work with TxDb objects directly

### ISSUE THREAD

**Issue by retaj** [BIMSBbioinfo/ciRcus#22]
Currently it loads an .sqlite using loadDb(), but there could also be a method with signature("TxDb") that chews a TxDb object already loaded into environment.

**Comment by mschilli87** [comment]
for reference: https://github.com/BIMSBbioinfo/ciRcus/blob/46dc98bd243b1a501e2434f5cc6705a51eadec7e/R/readData.R#L213-L229
