### ISSUE TITLE
Install library problems

### ISSUE THREAD

**Issue by KateK** [BIMSBbioinfo/ciRcus#5]
I tried to install ciRcus like it's described in readme, but it doesn't work. I got the error like this:

```
ERROR: dependencies ‘AnnotationHub’, ‘biomaRt’, ‘GenomicFeatures’ are not available for package ‘ciRcus’
```

I also tried to install it from source with the same error. Could you help ?

Thanks 

---
*edit (@mschilli87)*:  formatting

**Comment by frenkiboy** [comment]
Dear KateK, 

Thank you so much for using ciRcus!
The error means that you do not have all of the required packages installed.

if you do:

```r
source("https://bioconductor.org/biocLite.R")
biocLite(c('AnnotationHub','biomaRt','GenomicFeatures'))
```

You should be able to install ciRcus.

Please let me know if you have any other problems.

---
*edit (@mschilli87)*: formatting

**Comment by mschilli87** [comment]
I guess this can be closed.

**Comment by mschilli87** [comment]
@KateK: Please re-open this issue if @frenkiboy's solution doesn't work for you.
